import db from '../config/database.js';

export function generateMarkdownReport(reportType = 'executive') {
  const alerts = db.prepare('SELECT * FROM alerts ORDER BY timestamp DESC LIMIT 20').all();
  const incidents = db.prepare('SELECT * FROM incidents ORDER BY timestamp DESC LIMIT 10').all();
  const logsCount = db.prepare('SELECT COUNT(*) as total FROM logs').get().total;

  const dateStr = new Date().toISOString();

  if (reportType === 'forensic') {
    return `# SOCLab AI - Technical Forensic Incident Report
**Generated**: ${dateStr}
**Classification**: CONFIDENTIAL // INTERNAL USE ONLY

---

## 1. Executive Summary
During automated monitoring, SOCLab AI detected multi-stage threat activity across the local environment. Immediate containment procedures were initiated via SOAR Playbooks.

- **Total Logs Indexed**: ${logsCount}
- **Active Critical/High Alerts**: ${alerts.filter(a => a.severity === 'HIGH' || a.severity === 'CRITICAL').length}
- **Open Incidents**: ${incidents.filter(i => i.status === 'OPEN').length}

---

## 2. Recent Alert Evidentiary Audit
| Alert ID | Title | Severity | MITRE Technique | Status | Assigned To |
|---|---|---|---|---|---|
${alerts.map(a => `| ${a.id} | ${a.title} | **${a.severity}** | ${a.mitre_technique || 'N/A'} | ${a.status} | ${a.assigned_to} |`).join('\n')}

---

## 3. Threat Containment & Remediation Actions
1. **Host Isolation**: Triggered SOAR playbook PB-ISOLATE-HOST.
2. **Account Lockout**: Revoked active user credentials.
3. **Malware Purge**: Terminated malicious PIDs.

---
*Report generated by SOCLab AI Platform*
`;
  }

  return `# SOCLab AI - Executive Security & SOC Metrics Report
**Report Period**: Current Session (${dateStr})

---

## Key SOC Performance Metrics
- **Mean Time to Detect (MTTD)**: 45 seconds
- **Mean Time to Respond (MTTR)**: 3 minutes 12 seconds
- **Total Security Events Processed**: ${logsCount}
- **Active Rule Sets**: 15 Sigma Rules & YARA Scanners

## MITRE ATT&CK Tactic Coverage
- **Initial Access**: 100%
- **Execution**: 100%
- **Credential Access**: 95%
- **Persistence**: 90%
- **Command & Control**: 100%

---
*SOCLab AI Platform - Production Offline Edition*
`;
}
